apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfe-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfe-api
  template:
    metadata:
      labels:
        app: mfe-api
    spec:
      containers:
        - name: mfe-api
          image: localhost:5000/mfe-api:rel-0.0.15
          ports:
            - containerPort: 4000
